### ISSUE TITLE
设计网站主体整体布局

### ISSUE THREAD

**Issue by chenquan** [opensourceai/react-front-end#7]
要求:
1. 设计网站的整体布局
有疑惑,就联系 @chenquan

**Comment by chenquan** [comment]
UI图：https://hive.feishu.cn/drive/folder/fldcnMqnQ5Z4qK7VcXiP7GTELYb

**Comment by muzhoubai** [comment]
设计网站主体整体布局1.0：https://hive.feishu.cn/drive/folder/fldcnMqnQ5Z4qK7VcXiP7GTELYb
